### ISSUE TITLE
Following a code standard

### ISSUE THREAD

**Issue by imlinus** [flouthoc/scrollpup.js#1]
Hi there!

I've forked your library. And I wanna update the code standard.
Are you okay with me doing a pull request?

I'm following the StandardJS code standard === https://standardjs.com

Cheers,
Linus

**Comment by flouthoc** [comment]
@imlinus Yes pull request would be helpful

**Comment by imlinus** [comment]
Awesome!
I'll get on in straight after work

**Comment by imlinus** [comment]
Hi, please check my PR (https://github.com/flouthoc/scrollpup.js/pull/4)
