### ISSUE TITLE
Build tool

### ISSUE THREAD

**Issue by imlinus** [flouthoc/scrollpup.js#2]
Hi,

I'm about to add rollup (https://github.com/rollup/rollup) to your library,

As a build tool to take care of minifying (and probably other stuff in the future)

Are you okay with a PR?

Cheers,
Linus

**Comment by flouthoc** [comment]
@imlinus Please feel free to create any pull request

**Comment by imlinus** [comment]
Hi, please check my PR (https://github.com/flouthoc/scrollpup.js/pull/4)
