### ISSUE TITLE
Make it more dynamic

### ISSUE THREAD

**Issue by imlinus** [flouthoc/scrollpup.js#3]
Hi!

Right now most of the styling options are hard-coded,
What do you think about making them in to options instead?

Im thinking something like:
```js
scrollpup({
  background: 'linear-gradient(to right, #36d1dc, #5b86e5)',
  height: '5px'
})
```

Cheers,
Linus

**Comment by flouthoc** [comment]
@imlinus That's a great idea would you like to create a Pull Request

**Comment by imlinus** [comment]
Of course I will!
I'll get on it after work :-)

**Comment by imlinus** [comment]
Hi, please check my PR (https://github.com/flouthoc/scrollpup.js/pull/4)

**Comment by flouthoc** [comment]
:tada: Amazing !!!!!!
