### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by imlinus** [flouthoc/scrollpup.js#6]
What do you think about publishing the package to NPM for easier access?

https://www.npmjs.com/package/scrollpup is available, you could easily publish the package from your terminal 👍 

```
$ npm publish
```

Cheers,
Linus

**Comment by flouthoc** [comment]
@imlinus Thanks I'll add it ASAP :smiley:

**Comment by flouthoc** [comment]
Done! https://www.npmjs.com/package/scrollpup

**Comment by imlinus** [comment]
Proper!!

**Comment by imlinus** [comment]
Oh, and don't forget to update the Readme.
Maybe add something like: 

# Setup

```
$ npm i -S scrollpup
```

Cheers,
Linus
